#!/usr/bin/env python3
"""Build the report-facing PART-II summary from the raw rerun experiment CSV."""

import csv
from pathlib import Path


RAW_CSV = Path("results/rerun-20260611/paraphrase_experiments.csv")
SUMMARY_CSV = Path("results/report_summary_20260611.csv")


FIELDNAMES = [
  "section",
  "stage",
  "prompt_template",
  "bidirectional",
  "threshold",
  "train_examples",
  "dev_examples",
  "train_epochs",
  "train_batch_size",
  "train_grad_accum_steps",
  "eval_batch_size",
  "dev_acc",
  "dev_f1",
  "selected_threshold",
  "source_csv",
  "source_row",
  "artifact",
  "notes",
]


def load_rows():
  with RAW_CSV.open(newline="") as fp:
    reader = csv.DictReader(fp)
    return [(line_no, row) for line_no, row in enumerate(reader, start=2)]


def find_one(rows, *, output_tag, mode, predicate=None):
  matches = [
    (line_no, row)
    for line_no, row in rows
    if row["output_tag"] == output_tag and row["mode"] == mode
    and (predicate is None or predicate(row))
  ]
  if len(matches) != 1:
    raise RuntimeError(f"Expected one match for {output_tag}/{mode}, got {len(matches)}")
  return matches[0]


def find_all(rows, *, output_tag, mode):
  return [
    (line_no, row)
    for line_no, row in rows
    if row["output_tag"] == output_tag and row["mode"] == mode
  ]


def summary_row(
  line_no,
  row,
  *,
  section,
  stage,
  train_examples,
  dev_examples,
  train_epochs,
  train_batch_size,
  train_grad_accum_steps,
  eval_batch_size,
  artifact,
  notes,
):
  return {
    "section": section,
    "stage": stage,
    "prompt_template": row["prompt_template"],
    "bidirectional": row["bidirectional"],
    "threshold": row["selected_threshold"] or row["threshold"],
    "train_examples": train_examples,
    "dev_examples": dev_examples,
    "train_epochs": train_epochs,
    "train_batch_size": train_batch_size,
    "train_grad_accum_steps": train_grad_accum_steps,
    "eval_batch_size": eval_batch_size,
    "dev_acc": row["dev_acc"],
    "dev_f1": row["dev_f1"],
    "selected_threshold": row["selected_threshold"],
    "source_csv": str(RAW_CSV),
    "source_row": line_no,
    "artifact": artifact,
    "notes": notes,
  }


def main():
  rows = load_rows()
  selected = []

  for prompt in ["baseline", "direct", "meaning"]:
    tag = f"rerun-20260611-screen-{prompt}"
    line_no, row = find_one(rows, output_tag=tag, mode="dev_predict")
    selected.append(summary_row(
      line_no,
      row,
      section="prompt_screening",
      stage=prompt,
      train_examples="5000",
      dev_examples="1000",
      train_epochs="1",
      train_batch_size="4",
      train_grad_accum_steps="2",
      eval_batch_size="4",
      artifact=f"predictions/rerun-20260611/para-dev-screen-{prompt}.csv",
      notes="screening subset",
    ))

  line_no, row = find_one(
    rows,
    output_tag="rerun-20260611-full-direct",
    mode="dev_predict",
    predicate=lambda r: r["batch_size"] == "4",
  )
  full_direct_dev_rows = find_all(
    rows,
    output_tag="rerun-20260611-full-direct",
    mode="dev_predict",
  )
  if len(full_direct_dev_rows) > 1:
    full_direct_note = "raw CSV also contains a duplicate rerun row"
  else:
    full_direct_note = "single-direction dev prediction generated by train_dev"
  selected.append(summary_row(
    line_no,
    row,
    section="full_training",
    stage="full_direct",
    train_examples="full",
    dev_examples="full",
    train_epochs="3",
    train_batch_size="4",
    train_grad_accum_steps="2",
    eval_batch_size="4",
    artifact="predictions/rerun-20260611/para-dev-full-direct.csv",
    notes=full_direct_note,
  ))

  line_no, row = find_one(rows, output_tag="rerun-20260611-full-direct-bi", mode="dev_predict")
  selected.append(summary_row(
    line_no,
    row,
    section="ablation",
    stage="bidirectional",
    train_examples="full",
    dev_examples="full",
    train_epochs="3",
    train_batch_size="4",
    train_grad_accum_steps="2",
    eval_batch_size="8",
    artifact="predictions/rerun-20260611/para-dev-full-direct-bi.csv",
    notes="same checkpoint as full_direct",
  ))

  line_no, row = find_one(rows, output_tag="rerun-20260611-full-direct-bi-calib", mode="calibrate_dev")
  selected.append(summary_row(
    line_no,
    row,
    section="ablation",
    stage="threshold_calibration",
    train_examples="full",
    dev_examples="full",
    train_epochs="3",
    train_batch_size="4",
    train_grad_accum_steps="2",
    eval_batch_size="8",
    artifact=str(RAW_CSV),
    notes="threshold selected on dev",
  ))

  line_no, row = find_one(rows, output_tag="rerun-20260611-final", mode="test_predict")
  selected.append({
    "section": "final_output",
    "stage": "test_prediction",
    "prompt_template": row["prompt_template"],
    "bidirectional": row["bidirectional"],
    "threshold": row["threshold"],
    "train_examples": "full",
    "dev_examples": "NA",
    "train_epochs": "3",
    "train_batch_size": "4",
    "train_grad_accum_steps": "2",
    "eval_batch_size": row["batch_size"],
    "dev_acc": "",
    "dev_f1": "",
    "selected_threshold": "",
    "source_csv": str(RAW_CSV),
    "source_row": line_no,
    "artifact": "predictions/rerun-20260611/para-test-final.csv",
    "notes": "test labels unavailable",
  })

  SUMMARY_CSV.parent.mkdir(parents=True, exist_ok=True)
  with SUMMARY_CSV.open("w", newline="") as fp:
    writer = csv.DictWriter(fp, fieldnames=FIELDNAMES)
    writer.writeheader()
    writer.writerows(selected)


if __name__ == "__main__":
  main()
